version: '3.9'
services:
  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - rabbitmq
    networks:
      host:

  rabbitmq:
    image: rabbitmq:3.11-management
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      host:

networks:
  host:
